global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'analytics-api'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/metrics'
    
  - job_name: 'analytics-consumer'
    static_configs:
      - targets: ['consumer:8081']
    metrics_path: '/metrics'
    
  - job_name: 'clickhouse'
    static_configs:
      - targets: ['clickhouse:8123']
    metrics_path: '/metrics'